"""Execution / research states and first-gate vocabulary."""

from __future__ import annotations

from enum import StrEnum


class LeadLagState(StrEnum):
    OBSERVED = "OBSERVED"
    SIGNAL_REJECTED = "SIGNAL_REJECTED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    STALE_DATA = "STALE_DATA"
    UNSUPPORTED_RESOLUTION = "UNSUPPORTED_RESOLUTION"
    NOT_EXECUTABLE = "NOT_EXECUTABLE"
    NEGATIVE_CONSERVATIVE_NET = "NEGATIVE_CONSERVATIVE_NET"
    SHADOW_ADMITTED = "SHADOW_ADMITTED"
    HEDGE_UNAVAILABLE = "HEDGE_UNAVAILABLE"
    PAPER_PENDING = "PAPER_PENDING"
    PAPER_COMPLETED = "PAPER_COMPLETED"
    PAPER_FAILED = "PAPER_FAILED"


class DataQuality(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNSUPPORTED = "UNSUPPORTED"
